# Generated by Django 2.1 on 2018-08-09 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
